# Generated by Django 3.2 on 2021-04-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='categoryId',
        ),
    ]
