# Generated by Django 3.2 on 2021-04-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_category_books_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categoryId',
            new_name='category_id',
        ),
    ]
