# Generated by Django 3.2 on 2021-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
